services:
  backend:
    build: backend/
    tty: true
  backend-leaderboard:
    build: backend-leaderboard/
    volumes:
      - leaderboard-data:/etc/leaderboard-data
  frontend:
    build: ./
    ports:
      - "127.0.0.1:7780:80"
volumes:
  leaderboard-data:
